/**
 * A deck the app already knows.
 *
 * The drawn glyphs it renders for itself are a guess at what a card looks
 * like, and a guess is enough for a crisp, evenly lit table and not much else:
 * a real deck prints its index in its own typeface, a camera softens it, and a
 * blurred serif K matched against a drawn sans one loses to a digit.
 *
 * These are the real thing - the corner of each card, lifted from photographs
 * of an ordinary plastic deck on a dark table, taken with a phone at the
 * distance the scanner is actually used from. They are offered alongside the
 * drawn glyphs, so whichever fits better wins, and a deck taught through the
 * wizard replaces both.
 *
 * Ranks 2 to 7 are missing simply because those cards were not in the
 * photographs; the drawn glyphs still cover them.
 */
export const KNOWN_DECK = {
  ranks: {
    '10': { bits: 'AAAAAB/wAD8AAAP//AB/gAAH//8Af8AAH///wP/AAD////D/wAA////4/8AAf///+P/AAP////z/wAH////8/8AD/+A//P/AA/+AD/7/wAf/AAf+/8AH/wAH/v/AB/4AA///wAf8AAH//8AH/AAB///AD/wAAf//wA/8AAH//8AP+AAB///AD/gAAf//wA/4AAH//8AP+AAB///AD/gAAf//wA/4AAH//8AP+AAB///AD/gAAf//wA/4AAH//8AP+AAB///AD/gAAf//wA/4AAH//8AH+AAB///AB/gAAf//wAf4AAH//8AH+AAB///AB/gAAf//wAf4AAH//8AH+AAB///AB/gAAf//wAf4AAH//8AH+AAB///AB/gAAf//wAf4AAH//8AH+AAB///AB/gAAf//wAf4AAH//8AH+AAB///AB/gAAf//wAf4AAH//8AH+AAB///AB/gAAf//wAf4AAH//8AH+AAB///AB/wAAf//wAf8AAH//8AH/AAB///AB/wAAf//wAf8AAH//8AH/AAB///AB/gAAf//wAf4AAH//8AH/AAB///AB/wAAf//wAf8AAH//8AH/AAB///AB/wAAP//wAf8AAD//8AH/AAA///AB/wAAP//wAf8AAH//8AH/AAB///AB/wAAf//wAf8AAH//8AH/AAD///AB/wAA///wAf+AAP//8AH/gAH/3/AB/8AD/5/wAP/wB/+f8AD/+A//H/AAf////x/wAD////4f8AAf///8H/AAH///+B/wAA////Af8AAH///gH/AAAf//gB/gAAD//gAPgAAAAAAAA==', width: 56, height: 88, aspect: 0.5683 },
    '8': { bits: 'AAAAH8AAAAAAA///AAAAAA///4AAAAA////gAAAAf///+AAAAf////wAAAP////+AAAP/////wAAH/////+AAD//wA//wAA//wAH/+AAf/wAAf/gAH/4AAD/8AD/8AAAf/AA/+AAAD/wAP/AAAAf+AH/gAAAH/gB/4AAAA/8Af8AAAAP/AP/AAAAB/wD/wAAAAf8A/8AAAAH/AP/AAAAB/wD/wAAAAf8A/8AAAAH/AH/AAAAB/wB/4AAAA/8Af+AAAAP+AH/gAAAD/gA/8AAAB/wAP/gAAA/8AD/4AAAf/AAf/AAAP/gAD/4AAH/4AA//gAH/8AAH//AP/+AAA//////AAAH/////gAAAf////wAAAH////wAAAB////8AAAB/////AAAA/////4AAAf/////AAAf/////4AAP//////gAH//wB//8AD//AAD//AB//AAAH/4A//gAAA//AP/wAAAH/wD/4AAAA/+B/4AAAAH/g/+AAAAA/8P/AAAAAP/D/wAAAAB/4/4AAAAAf+f+AAAAAH/n/gAAAAA/9/4AAAAAP/f+AAAAAD/3/AAAAAA/9/4AAAAAH/f+AAAAAB///gAAAAA///4AAAAAP//+AAAAAD/3/gAAAAB/9/8AAAAAf+P/AAAAAH/j/wAAAAD/w/+AAAAA/8P/wAAAAf/B/+AAAAf/gP/wAAAP/4D/+AAAH/8A//wAAD//AH//gAD//gA//8AD//wAH//////4AA//////8AAH/////+AAA/////+AAAD/////AAAAf////AAAAB////gAAAAH///AAAAAAP/+AAAA==', width: 56, height: 88, aspect: 0.5985 },
    '9': { bits: 'AAAD/+AAAAAAP//+AAAAAH///4AAAAH////gAAAD////+AAAD/////wAAB/////+AAA//////wAAf//7//+AAH/+AH//wAD/8AAP/+AD/+AAB//gA//AAAH/4AP/gAAA//AH/gAAAH/4D/wAAAA/+B/8AAAAH/wf+AAAAA/8H/AAAAAP/D/wAAAAD/w/4AAAAAf+P+AAAAAH/j/gAAAAA/4/wAAAAAP+f8AAAAAD/n/AAAAAAf9/wAAAAAH/f4AAAAAB//+AAAAAAf//gAAAAAH//4AAAAAB//+AAAAAAf//gAAAAAH//4AAAAAB//+AAAAAAf//gAAAAAH/f4AAAAAD/3+AAAAAA/9/wAAAAAP/f8AAAAAH/z/AAAAAB/8/4AAAAAf/P+AAAAAP/z/wAAAAD/8f8AAAAB//H/gAAAAf/g/8AAAAP/4P/gAAAH/+B/4AAAD//gf/AAAB//4H/4AAAf/+A//AAAf//gP/8AAf//4A//gAf//8AP///////AB///////wAH////+/8AB/////P/AAH////D/wAAf///A/8AAB///AP+AAAH//AD/gAAAAAAA/4AAAAAAAf+AAAAAAAH/AAAAAAAB/wAAAAAAA/4AAAAAAAP+AAAAAAAH/gAAAAAAB/4AAAAAAAf8Af4AAAAP/AH/AAAAH/gB/4AAAB/4Af/AAAA/8AD/4AAAf/AA//AAAP/gAH/4AAH/wAB//gAP/4AAP/+AP/+AAD//////AAAP/////AAAD/////wAAAf////wAAAB////4AAAAP///4AAAAB///8AAAAAB//4AAAA==', width: 56, height: 88, aspect: 0.5556 },
    'A': { bits: 'AAAAH8AAAAAAAD/gAAAAAAB/4AAAAAAAf+AAAAAAAH/gAAAAAAB/4AAAAAAAf+AAAAAAAP/gAAAAAAH/8AAAAAAB//AAAAAAAf/wAAAAAAH/+AAAAAAB//gAAAAAAf/4AAAAAAP/+AAAAAAD//gAAAAAA//4AAAAAAf//AAAAAAH//wAAAAAB//8AAAAAAf//gAAAAAP//4AAAAAD//+AAAAAA///gAAAAAP//4AAAAAH//+AAAAAB/x/gAAAAAf8f4AAAAAH/H/AAAAAB/x/wAAAAA/4f8AAAAAP+D/AAAAAD/g/wAAAAB/4P+AAAAAf8D/gAAAAH/A/4AAAAB/wP+AAAAAf8B/wAAAAP/Af8AAAAD/gH/AAAAA/4B/4AAAAP+Af+AAAAH/AH/gAAAB/wA/4AAAAf8AP/AAAAH/AD/wAAAB/wA/8AAAA/8AP/AAAAP+AD/wAAAD/gAf8AAAB/4AH/AAAAf8AB/wAAAH/AAP+AAAB/wAD/gAAA/8AA/8AAAP/AAP/AAAD/wAD/wAAA/8AA/8AAAf/gAf/AAAH/////wAAB/////8AAAf/////gAAP/////4AAD/////+AAA//////gAAP/////8AAD//////AAB//////wAAf+AAB/8AAP/AAAP/AAD/wAAB/wAA/8AAAf+AAP+AAAH/gAD/gAAB/4AA/4AAAP/AAf+AAAD/wAH/AAAA/8AD/4AAAP/Af//AAAH/4P///gB///7///8Af///////AH///////wB///////8A////////AH///////wB///////4Af///AAAAAAz//g==', width: 56, height: 88, aspect: 0.5985 },
    'J': { bits: 'AAAAB/4AfgAAAAf///8AAAAH////AAAAB////wAAAAf///8AAAAH////AAAAB////wAAAAf///4AAAAH7//+AAAAAAP/8AAAAAAD/4AAAAAAA/+AAAAAAAP/gAAAAAAD/4AAAAAAA/+AAAAAAAP/gAAAAAAD/4AAAAAAA/+AAAAAAAP/gAAAAAAD/4AAAAAAA/+AAAAAAAP/gAAAAAAD/4AAAAAAA/+AAAAAAAP/gAAAAAAD/4AAAAAAA/+AAAAAAAP/gAAAAAAD/4AAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP/AAAAAAAD/wAAAAAAA/8AAAAAAAP+AAAAAAAD/gA/gAAAA/4Af8AAAAP+AH/AAAAD/wD/wAAAA/8A/8AAAAP/AP/AAAAD/wD/wAAAA/8A/+AAAAf+AP/gAAAH/gB/4AAAD/4Af+AAAA/+AH/wAAAP/gB/8AAAD/4AP/gAAB/+AD/4AAAf/AA//AAAP/wAP/4AAH/4AB//AAD/+AAP/4AB//AAD//gD//wAA///P//4AAH/////8AAAf////+AAAH/////gAAAf////gAAAD////wAAAAf///wAAAAB///4AAAAAH//wAAAA==', width: 56, height: 88, aspect: 0.5896 },
    'K': { bits: 'P/+/APwAEH///4H///5///+D////f///gf///3///wH///9///8B////f///A////3///wH///9///8B////f///AP///gH//AAf/wgB/8AAH/4AAf/AAB/+AAD/gAA//AAA/8AAP/gAAP/AAH/4AAD/wAB/8AAA/8AA/+AAAP/AAf/gAAD/wAH/wAAA/8AD/4AAAP/AB/+AAAD/wAf/AAAA/8AP/wAAAP/AH/4AAAD/wB/+AAAA/8A//AAAAP/AP/wAAAD/wH/4AAAA/8D/8AAAAP/A/+AAAAD/wf/gAAAA/8H/wAAAAP+D/4AAAAD/h/+AAAAA/8f/gAAAAP/P/4AAAAD///+AAAAA////gAAAAP///4AAAAH////AAAAB////wAAAAf///+AAAAH////gAAAB////8AAAAf////AAAAH////4AAAB//+f+AAAAf//H/wAAAH//g/8AAAB//wP/AAAAf/8D/4AAAH/+Af+AAAB//gH/gAAAf/wA/8AAAH/4AP/AAAB/+AD/4AAAf/gA/+AAAH/wAH/wAAB/8AB/8AAAf+AAf/AAAH/gAD/wAAB/4AA/+AAAf+AAP/gAAH/gAB/8AAB/4AAf/gAAf+AAD/4AAH/gAA/+AAB/8AAP/gAAf/AAB/8AAH/wAAf/AAB/8AAD/wAAf/AAAf+AAH/gAAH/gAB/4AAB/4AA/+AAAf/AAP/wAAH/wAH/+AAB/+A///+Af///v///wP///////8D////////A////////wP///////8D////////A////////wP///////4D///+f//+Af///g==', width: 56, height: 88, aspect: 0.5882 },
    'Q': { bits: 'AAAAEAAAAAAAAf/4AAAAAAf//gAAAAAf//+AAAAAf///wAAAAf////AAAAP////4AAAH////+AAAB/////4AAA/////+AAAP/////wAAH/+A//8AAB/+AA//AAA//AAH/4AAP/gAA/+AAH/wAAH/wAB/8AAB/8AAf/AAAP/AAH/gAAD/wAB/4AAA/8AAf+AAAP/AAH/gAAD/wAB/4AAA/8AAf+AAAP/AAH/gAAD/wAB/4AAA/8AAf+AAAP/AAH/gAAH/wAB/4AAB/8AAf+AAAf/AAH/gAAH/wAB/4AAB/4AAf+AAAf+AAH/gAAH/gAB/4AAB/4AAf+AAAf+AAH/gAAH/gAB/4AAB/4AAf+AAAf+AAH/gAAH/gAB/4AAB/8AAf8AAAf/AAH/AAAH/wAB/wAAB/8AAf8AAAf/AAH/AAAH/wAB/wAAB/8AA/+AAAf+AAP/gAAH/gD//4AAB/4D//+AAAf+A///wAAH/gP///gAB/4D////AAf+A////4AH/gP////AB/4D////4Af+Af////AH/gD////4B/4AB////Af+AAP///4H/gAD////B/4AAf///wf+AAH/j/8H/gAB/4f/x/4AA/8D/8/+AAP/Af///gAD/wD///4AA/8Af//+AAP/AD///AAD/4A///wAA/+AH//8AAH/wA///AAB/8AP//4AAf/wB//+AAH/+Af//wAA//wH///AAP//////+AB///////wAP//////8AD///////AAf//////wAD//////8AAP//////AAB//////wAAP//+Af8AAB///AD/AAAD/+AAHg==', width: 56, height: 88, aspect: 0.5429 },
  },
  suits: {
    'c': { bits: 'AAAAGAAAAAAAAH/AAAAAAAH/8AAAAAAD//gAAAAAD//8AAAAAA///gAAAAAf//4AAAAAP///AAAAAD///wAAAAB///+AAAAAf///gAAAAH///8AAAAB////AAAAA////wAAAAP///8AAAAD////AAAAA////wAAAAP///8AAAAB////AAAAAf///wAAAAH///4AAAAA///+AAAAAP///AAAAAD///wAAAAAf//8AAAAAH///AAAAAA///gAAAAAH//4AAAAAB//8AAAAfwP/+DgAAP/n//h/AAP//////8AH///////gD///////8B////////g////////8P////////n////////5////////+f/////////////////////////////////////////////////////////////////////////9/////////f///fn///3///z5///9///4+f//+P//+Pj///j///D4///4f//x+H//8H//4fh//+A//8H4P//gP//B+D//wB//gfgf/4AH/gH4B/8AAHgD/AD8AAAAA/wAAAAAAAP8AAAAAAAH/gAAAAAAB/4AAAAAAAf+AAAAAAAH/wAAAAAAB/8AAAAAAAf/AAAAAAAP/wAAAAAAD/8AAAAAAA//AAAAAAAP/gAAA', width: 56, height: 72, aspect: 0.8922 },
    'd': { bits: 'AAAAHAAAAAAAABwAAAAAAAB+AAAAAAAAfwAAAAAAAP8AAAAAAAH/gAAAAAAB/8AAAAAAAf/AAAAAAAP/wAAAAAAD/+AAAAAAB//wAAAAAA//+AAAAAAf//gAAAAAP//+AAAAAH///gAAAAB///8AAAAA////AAAAAf///4AAAAP////gAAAD////4AAAB/////AAAA/////4AAAf////+AAAP/////wAAH/////+AAD//////wAB//////+AA///////wAP//////+AH///////wD///////8D////////w////////8f////////v//////////////////////////////////////////////f////////j////////wf///////4D///////8Af//////+AH///////gA///////wAH//////wAA//////4AAD/////8AAAf/////AAAH/////gAAB/////wAAAP////8AAAB////+AAAAP///+AAAAB////gAAAAP///wAAAAD///8AAAAAf//+AAAAAD///AAAAAAf//gAAAAAH//wAAAAAA//4AAAAAAH/8AAAAAAA//AAAAAAAP/gAAAAAAB/4AAAAAAAf4AAAAAAAD+AAAAAAAA/AAAAAAAAHwAAAAAAAA4AAAA', width: 56, height: 72, aspect: 0.6667 },
    'h': { bits: 'AB/gAAPwAAD//AAf/gAB//4AP/+AA//+AP//wAf//wH//+Af///B///wH///wf//+D///8P///w////j///8P///4////n///+P///5////j///+f///5////////////////////////////////////////////////////////////////////////////////////////3////////9////////+f////////n////////4////////8P////////D////////w////////8P///////+B////////gf///////wH///////8A///////+AH///////gB///////4Af//////8AD///////AA///////gAH//////wAB//////8AAP//////AAD//////gAAP/////wAAD/////8AAAf////+AAAH/////AAAAf////gAAAH////4AAAB////8AAAAP///+AAAAB////AAAAAf///wAAAAD///4AAAAA///8AAAAAD///AAAAAA///gAAAAAP//4AAAAAB//8AAAAAAP/+AAAAAAD//gAAAAAAf/wAAAAAAD/4AAAAAAA/8AAAAAAAH/AAAAAAAB/gAAAAAAAP4AAAAAAAD8AAAAAAAAfAAAAAAAAHwAAAAAAAA4AAAA', width: 56, height: 72, aspect: 0.713 },
    's': { bits: 'AAAAMAAAAAAAADwAAAAAAAB+AAAAAAAA/gAAAAAAAf8AAAAAAAH/AAAAAAAB/4AAAAAAA//AAAAAAAf/4AAAAAAH/+AAAAAAH//wAAAAAB//+AAAAAA///wAAAAAP//8AAAAAH///gAAAAD///8AAAAB////gAAAA////8AAAAf////gAAAH////4AAAD/////AAAB/////4AAA//////AAAP/////wAAH/////+AAD//////wAA//////+AAf//////wAH//////8AD///////gB///////4Af///////AP///////4D///////+B////////wf///////8P////////D////////4////////+f////////n////////////////////////////////////////////////////////////////////////////////////////9////////+P//////+Pj///////j4f//5///w8H//+P//8PA///D//+DwP//gf//g+B//4D//wPgf/8Af/4D4D/+AD/8A+AP+AAfwAfgAAAAAAAH4AAAAAAAD/AAAAAAAA/wAAAAAAAP8AAAAAAAH/AAAAAAAB/4AAAAAAAf/AAAAAAAH/wAAAAAAB/+AAAAAAA//gAAAAAAP/wAAA', width: 56, height: 72, aspect: 0.6875 },
  },
};
